const data = [
    {
        id: 1,
        date: "12 Dec 2019",
        location: "Sheffield, UK",
        description: "I paused my masters but decided to stick around for no reason whatsoever. I guess I was sensing all the fun ahead.",
        image: "./images/01.jpg",
    },
    {
        id: 2,
        date: "23 Dec 2019",
        location: "Wuhan, China",
        description: "At this stage Wuhan went into complete lockdown. Hehehe...and my oblivious self was making plans for a restful holiday.",
        image: "./images/02.jpg",
    },
    {
        id: 3,
        date: "28 Jan 2020",
        location: "Manchester, UK",
        description: "Many chinese students started to wear masks at this point. Me ignoring everything, I went and applied for a Schengen visa.",
        image: "./images/03.jpg",
    },
    {
        id: 4,
        date: "6 Feb 2020",
        location: "Basel, Switzerland",
        description: "Plane got delayed and eventually cancelled due to a hurricane kinda situation. But, hey those two extra days were the best of the trip!",
        image: "./images/04.jpg",
    },
    {
        id: 5,
        date: "7 March 2020",
        location: "Peak District, UK",
        description: "My friends and I booked a cottage in the middle of nowhere. We spent all our days walking in fields and chasing sheeps with no idea whats happening in the world.",
        image: "./images/05.jpg",
    },
    {
        id: 6,
        date: "10 March 2020",
        location: "Sheffield, UK",
        description: "Came back and the city was in complete mess. Supermarkets were getting out of stock and everyone was paranoid. Did I process yet?",
        image: "./images/06.jpg",
    },
    {
        id: 7,
        date: "13 March 2020",
        location: "London, UK",
        description: "Me still being naive and not getting what all the fuss is about, I went to London to visit an old friend and get a 2 hours haircut session.",
        image: "./images/07.jpg",
    },
    {
        id: 8,
        date: "15 March 2020",
        location: "Sheffield, UK",
        description: "Okaaay, at last I get it. Here, the embassy was urging us to return home as soon as possible. Booked a train and went back to Sheffield.",
        image: "./images/08.jpg",
    },
    {
        id: 9,
        date: "17 March 2020",
        location: "Sheffield, UK",
        description: "Booked the earliest flight...then it got cancelled...booked again different airline...got cancelled...booked again for the 23rd.",
        image: "./images/09.jpg",
    },
    {
        id: 10,
        date: "23 March 2020",
        location: "Manchester, UK",
        description: "Went to the airport but the airline refused our entry. My friends and I were so stressed we just sat there and played Switch. Eventually we booked again with another airline. ",
        image: "./images/10.jpg",
    },
    {
        id: 11,
        date: "24 March 2020",
        location: "Manchester, UK",
        description: "Our flight got cancelled again. The hotels were closing so they asked us to leave. Lol for half a day, we were homeless with 15 bags.",
        image: "./images/11.jpg",
    },
    {
        id: 12,
        date: "25 March 2020",
        location: "Manchester, UK",
        description: "Luckly, airlines were starting to refuse non-nationals so we were able to find a flight. How will we make it to Heathrow though when trains are also getting cancelled? No idea.",
        image: "./images/12.jpg",
    },
    {
        id: 13,
        date: "26 March 2020",
        location: "London, UK",
        description: "Initially, our solution was to sit and play UNO. That obviously didn't work, so we called the embassy who generously sent us a ride.",
        image: "./images/13.jpg",
    },
]; 

export default data; 